### ISSUE TITLE
Add language support for assigning properties to features

### ISSUE THREAD

**Issue by sprocter** [osate/osate2-gtse#22]
The language should support assigning properties to features.

Example input:

```
configuration cpu_power_scaling (
	power: SEI::PowerBudget from (0.1W .. 300W)
) extends impl::platform::platform.federated {
	cpu.power#SEI::PowerBudget => power
}
```

Example output:

```
PropertyValue-bscu.platform.cpu2.power-SEI\:\:PowerBudget-float=0.1,300.0
```

**Comment by lwrage** [comment]
Property values can be assigned to features, already. What's missing is

1. Support parameters as property values.
2. Use a single range value in the parameter candidate list as a distribution model for the engine configuration API.

Note: The candidate list was originally introduced as an enumeration of possible values that the parameter could take.
